cababa/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.top_view, name='top_view'),
    path('user_agreement/', views.user_agreement_view, name='user_agreement_view'),
    path('cast_agreement/', views.cast_agreement_view, name='cast_agreement_view'),
    path('privacy_policy/', views.privacy_policy_view, name='privacy_policy_view'),
    path('cancel_policy/', views.cancel_policy_view, name='cancel_policy_view'),
    path('specified_commercial_transactions_act/', views.specified_commercial_transactions_act_view, name='specified_commercial_transactions_act_view'),
    path('system/', views.system_view, name='system_view'),
    path('admin/', admin.site.urls),
    path('pre_register/', include('pre_register.urls')),
    path('guest/', include('guest.urls')),
    path('hostess/', include('hostess.urls')),
    path('reservations/', include('reservations.urls')),
    path('staff/', include('staff.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guest/urls.py
from django.urls import path

from . import views

app_name = 'guest'

urlpatterns = [
    path('login/', views.GuestLoginView.as_view(), name='login'),
    path('callback/', views.GuestLoginCallbackView.as_view(), name='login_callback'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup/done/', views.SignUpDoneView.as_view(), name='signup_done'),
    path('bot/webhook/', views.LineBotWebhookView.as_view(), name='bot_webhook'),
]

reservations/urls.py
from django.urls import path

from . import views

app_name = 'reservations'

urlpatterns = [
    path('hostess/', views.HostessListView.as_view(), name='hostess_list'),
    path('hostess/search/', views.HostessSearchView.as_view(), name='hostess_search'),
    path('hostess/detail/', views.HostessDetailTestView.as_view(), name='hostess_detail_test'),
    path('hostess/<str:hostess_id>/', views.HostessDetailView.as_view(), name='hostess_detail'),
    path('<str:available_id>/new/', views.CreateReserveView.as_view(), name='create_reserve'),
    path('<str:reservation_id>/done/', views.DoneReserveView.as_view(), name='done_reserve'),
    path('<str:reservation_id>/pay/authorize/', views.ReserveAuthorizeView.as_view(), name='pay_authorize'),
    path('<str:reservation_id>/pay/cancel/', views.ReserveCancelView.as_view(), name='pay_cancel'),
]

cababa/views.py
import os
import csv
import markdown

from django.shortcuts import render
from django.utils.html import html_safe


def top_view(request):
    BASE_DIR = os.path.abspath(os.path.dirname(__file__))
    csv_file = os.path.join(BASE_DIR, 'data/faq.csv')
    with open(csv_file, 'r', encoding='utf8') as f:
        reader = csv.reader(f)
        headers = next(reader)
        faqs = [dict(question=row[0], answer=row[1]) for row in reader]
    context = dict(faqs=faqs)
    return render(request, 'cababa/index.html', context=context)


def markdown_html(filename):
    BASE_DIR = os.path.abspath(os.path.dirname(__file__))
    agreement_text = os.path.join(BASE_DIR, 'data/{}.md'.format(filename))
    with open(agreement_text, 'r', encoding='utf8') as f:
        md_text = f.read()
    md = markdown.Markdown()
    md_text = md.convert(md_text)
    return md_text


def user_agreement_view(request):
    context = dict(md_text=markdown_html('user_agreement'))
    return render(request, 'cababa/agreement.html', context=context)


def cast_agreement_view(request):
    context = dict(md_text=markdown_html('cast_agreement'))
    return render(request, 'cababa/agreement.html', context=context)


def privacy_policy_view(request):
    context = dict(md_text=markdown_html('privacy_policy'))
    return render(request, 'cababa/agreement.html', context=context)


def cancel_policy_view(request):
    context = dict(md_text=markdown_html('cancel_policy'))
    return render(request, 'cababa/agreement.html', context=context)


def specified_commercial_transactions_act_view(request):
    context = dict(md_text=markdown_html('specified_commercial_transactions_act'))
    return render(request, 'cababa/agreement.html', context=context)

def system_view(request):
    return render(request, 'cababa/system.html')

cababa/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}{% endblock %} | CABABA</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{% block description %}{% endblock %}">
	<meta name="keywords" content="{% block keywords %}{% endblock %}">
	<link rel="stylesheet" href="{% static 'tp_gold/css/style.css' %}">
	{% block stylesheet %}{% endblock %}
	<script src="{% static 'tp_gold/js/openclose.js' %}"></script>
	<script src="{% static 'tp_gold/js/fixmenu_pagetop.js' %}"></script>
	<script src="{% static 'tp_gold/js/fixmenu.js' %}"></script>
	<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="home">

	<!-- トップタイトルヘッダー -->
	{% include 'partials/header.html' %}

	<!--PC用（801px以上端末）メニュー-->
	{% include 'partials/menubar.html' %}
	<!--小さな端末用（800px以下端末）メニュー-->
	{% include 'partials/menubar-s.html' %}

	<!--スライドショー-->
	{% include 'partials/mainimg.html' %}


	<div id="contents" class="inner">
		<div id="contents-in">

			<div id="main">
				{% block content %}
				{% endblock %}
			</div>
			<!--/main-->

			<div id="sub">
				{% include 'partials/sub.html' %}
			</div>
			<!--/#sub-->

		</div>
		<!--/#contents-in-->

		<div id="side">
			{% include 'partials/side.html' %}
		</div>
		<!--/#side-->

	</div>
	<!--/#contents-->

	<footer>

		<div id="footermenu" class="inner">
			{% include 'partials/footermenu.html' %}
		</div>
		<!--/footermenu-->

		<div id="copyright">
			{% include 'partials/copyright.html' %}
		</div>

	</footer>

	<!--ページの上部に戻る「↑」ボタン-->
	<p class="nav-fix-pos-pagetop"><a href="#">↑</a></p>

	<!--メニュー開閉ボタン-->
	<div id="menubar_hdr" class="close"></div>
	<!--メニューの開閉処理条件設定　800px以下-->
	<script>
		if (OCwindowWidth() <= 800) {
			open_close("menubar_hdr", "menubar-s");
		}
	</script>

	{% block script %}{% endblock %}

</body>

</html>

cababa/templates/partials/copyright.html
<small>Copyright&copy; <a href="/">CABABA</a> All Rights Reserved.</small>

cababa/templates/partials/footermenu.html
<!-- <ul>
    <li class="title">メニュータイトル</li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
</ul>
<ul>
    <li class="title">メニュータイトル</li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
</ul>
<ul>
    <li class="title">メニュータイトル</li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
</ul>
<ul>
    <li class="title">メニュータイトル</li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
    <li><a href="#">メニューサンプルメニューサンプル</a></li>
</ul> -->

cababa/templates/partials/header.html
{% load static %}
<header>
    <div class="inner">
        <h1 id="logo"><a href="{% url 'top_view' %}"><img src="{% static 'tp_gold/images/logo.png' %}" alt="SAMPLE COMPANY"></a></h1>
        <!-- <div id="contact">
            <p class="tel">TEL:00-0000-0000<span>受付：00:00〜00:00　定休日：水曜日</span></p>
        </div> -->
    </div>
</header>

cababa/templates/partials/mainimg.html
{% load static %}
<aside id="mainimg">
	<img src="{% static 'tp_gold/images/1.jpg' %}" alt="" class="slide0">
	<img src="{% static 'tp_gold/images/1.jpg' %}" alt="" class="slide1">
	<img src="{% static 'tp_gold/images/2.jpg' %}" alt="" class="slide2">
	<img src="{% static 'tp_gold/images/3.jpg' %}" alt="" class="slide3">
</aside>

cababa/templates/partials/menubar-s.html
<nav id="menubar-s">
    <ul>
        <li><a href="{% url 'top_view' %}">HOME<span>ホーム</span></a></li>
        <li><a href="{% url 'reservations:hostess_search' %}">CAST<span>キャスト</span></a></li>
        <li><a href="{% url 'system_view' %}">SYSTEM<span>システム</span></a></li>
        <!-- <li><a href="recruit.html">RECRUIT<span>キャスト募集</span></a></li> -->
    </ul>
</nav>

cababa/templates/partials/menubar.html
<!--PC用（801px以上端末）メニュー-->
<nav id="menubar" class="nav-fix-pos">
    <ul class="inner">
        <li><a href="{% url 'reservations:hostess_search' %}">CAST<span>キャスト</span></a></li>
        <li><a href="{% url 'system_view' %}">SYSTEM<span>システム</span></a></li>
        <!-- <li class="current"><a href="recruit.html">RECRUIT<span>キャスト募集</span></a></li> -->
    </ul>
</nav>

cababa/templates/partials/side.html
{% load static %}
<!-- <nav>
    <h2>Contents</h2>
    <ul class="submenu">
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
    </ul>
</nav> -->

<!-- <section>

    <h2>人気キャスト</h2>

    <div class="list-sub">
        <a href="staff.html">
            <figure><img src="{% static 'tp_gold/images/photo1.png' %}" alt=""></figure>
            <h4>sample name</h4>
            <p>簡単な説明を入れます。</p>
        </a>
    </div>

    <div class="list-sub">
        <a href="staff.html">
            <figure><img src="{% static 'tp_gold/images/photo1.png' %}" alt=""></figure>
            <h4>sample name</h4>
            <p>簡単な説明を入れます。</p>
        </a>
    </div>

    <div class="list-sub">
        <a href="staff.html">
            <figure><img src="{% static 'tp_gold/images/photo1.png' %}" alt=""></figure>
            <h4>sample name</h4>
            <p>簡単な説明を入れます。</p>
        </a>
    </div>

    <div class="list-sub">
        <a href="staff.html">
            <figure><img src="{% static 'tp_gold/images/photo1.png' %}" alt=""></figure>
            <h4>sample name</h4>
            <p>簡単な説明を入れます。</p>
        </a>
    </div>

</section> -->

<p>
    <!-- <a href="recruit.html"><img src="{% static 'tp_gold/images/banner1.jpg' %}" alt="採用情報" class="pc border1"></a>
    <a href="recruit.html"><img src="{% static 'tp_gold/images/banner1_sh.jpg' %}" alt="採用情報" class="sh border1"></a> -->
</p>

cababa/templates/partials/sub.html
<!-- <nav class="box1">
    <h2>Contents</h2>
    <ul class="submenu">
        <li><a href="company.html">会社概要</a></li>
        <li><a href="link.html">リンク</a></li>
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
    </ul>
</nav> -->

<!-- <nav class="box1">
    <ul class="submenu">
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
        <li><a href="#">メニューサンプル</a></li>
    </ul>
</nav> -->

<!-- <div class="box1 c">
    <h2 class="mb10">アクセス</h2>
    <p>東京都XX区XXXXビル３F<br>
        TEL：03-0000-0000<br>
        定休日：月曜日</p>
</div> -->