cababa/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.top_view, name='top_view'),
    path('user_agreement/', views.user_agreement_view, name='user_agreement_view'),
    path('cast_agreement/', views.cast_agreement_view, name='cast_agreement_view'),
    path('privacy_policy/', views.privacy_policy_view, name='privacy_policy_view'),
    path('cancel_policy/', views.cancel_policy_view, name='cancel_policy_view'),
    path('specified_commercial_transactions_act/', views.specified_commercial_transactions_act_view, name='specified_commercial_transactions_act_view'),
    path('system/', views.system_view, name='system_view'),
    path('admin/', admin.site.urls),
    path('pre_register/', include('pre_register.urls')),
    path('guest/', include('guest.urls')),
    path('hostess/', include('hostess.urls')),
    path('reservations/', include('reservations.urls')),
    path('staff/', include('staff.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guest/urls.py
from django.urls import path

from . import views

app_name = 'guest'

urlpatterns = [
    path('login/', views.GuestLoginView.as_view(), name='login'),
    path('callback/', views.GuestLoginCallbackView.as_view(), name='login_callback'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup/done/', views.SignUpDoneView.as_view(), name='signup_done'),
    path('bot/webhook/', views.LineBotWebhookView.as_view(), name='bot_webhook'),
]

pre_register/urls.py
from django.urls import path

from . import views

app_name = 'pre_register'

urlpatterns = [
    path('', views.PreRegistrationView.as_view(), name='form'),
    path('done/', views.pre_registration_done_view, name='done'),
]

reservations/urls.py
from django.urls import path

from . import views

app_name = 'reservations'

urlpatterns = [
    path('hostess/', views.HostessListView.as_view(), name='hostess_list'),
    path('hostess/search/', views.HostessSearchView.as_view(), name='hostess_search'),
    path('hostess/detail/', views.HostessDetailTestView.as_view(), name='hostess_detail_test'),
    path('hostess/<str:hostess_id>/', views.HostessDetailView.as_view(), name='hostess_detail'),
    path('<str:available_id>/new/', views.CreateReserveView.as_view(), name='create_reserve'),
    path('<str:reservation_id>/done/', views.DoneReserveView.as_view(), name='done_reserve'),
    path('<str:reservation_id>/pay/authorize/', views.ReserveAuthorizeView.as_view(), name='pay_authorize'),
    path('<str:reservation_id>/pay/cancel/', views.ReserveCancelView.as_view(), name='pay_cancel'),
]

cababa/views.py
import os
import csv
import markdown

from django.shortcuts import render
from django.utils.html import html_safe


def top_view(request):
    BASE_DIR = os.path.abspath(os.path.dirname(__file__))
    csv_file = os.path.join(BASE_DIR, 'data/faq.csv')
    with open(csv_file, 'r', encoding='utf8') as f:
        reader = csv.reader(f)
        headers = next(reader)
        faqs = [dict(question=row[0], answer=row[1]) for row in reader]
    context = dict(faqs=faqs)
    return render(request, 'cababa/index.html', context=context)


def markdown_html(filename):
    BASE_DIR = os.path.abspath(os.path.dirname(__file__))
    agreement_text = os.path.join(BASE_DIR, 'data/{}.md'.format(filename))
    with open(agreement_text, 'r', encoding='utf8') as f:
        md_text = f.read()
    md = markdown.Markdown()
    md_text = md.convert(md_text)
    return md_text


def user_agreement_view(request):
    context = dict(md_text=markdown_html('user_agreement'))
    return render(request, 'cababa/agreement.html', context=context)


def cast_agreement_view(request):
    context = dict(md_text=markdown_html('cast_agreement'))
    return render(request, 'cababa/agreement.html', context=context)


def privacy_policy_view(request):
    context = dict(md_text=markdown_html('privacy_policy'))
    return render(request, 'cababa/agreement.html', context=context)


def cancel_policy_view(request):
    context = dict(md_text=markdown_html('cancel_policy'))
    return render(request, 'cababa/agreement.html', context=context)


def specified_commercial_transactions_act_view(request):
    context = dict(md_text=markdown_html('specified_commercial_transactions_act'))
    return render(request, 'cababa/agreement.html', context=context)

def system_view(request):
    return render(request, 'cababa/system.html')

cababa/templates/cababa/agreement.html
{% load markdownify %}

{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    <title>CABABA</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <nav>
        <a href="/">
            <img src="{% static 'images/title.svg' %}" alt="">
        </a>
    </nav>
    <div class="markdown">
        {{ md_text|safe }}
    </div>

    {% include 'cababa/partials/footer.html' %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'main.js' %}"></script>
    {% include 'cababa/partials/google_tag.html' %}
</body>
</html>

cababa/templates/cababa/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    <title>CABABA</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <header>
        <a href="{% url 'reservations:hostess_list' %}">
        <!-- <a href="{% url 'pre_register:form' %}"> -->
            <button>今すぐお話する</button>
            <!-- <button>キャスト事前登録はコチラ</button> -->
        </a>
    </header>

    <img class="flyer" src="{% static 'images/about.jpg' %}" alt="about">
    <img class="flyer" src="{% static 'images/flows.jpg' %}" alt="flows">
    <img class="flyer" src="{% static 'images/plans.jpg' %}" alt="plans">

    <div class="faq">
        <h3 class="faq-title">FAQ</h3>

        {% for faq in faqs %}
            <div class="faq-content">
                <div class="question" id="faq-{{ forloop.counter }}">
                    <span>Q</span>
                    <p>{{ faq.question }}</p>
                </div>
                <div class="answer" aria-labelledby="faq-{{ forloop.counter }}">
                    <span>A</span>
                    <p>{{ faq.answer }}</p>
                </div>
            </div>
        {% endfor %}

    </div>

    {% include 'cababa/partials/footer.html' %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'main.js' %}"></script>
    {% include 'cababa/partials/google_tag.html' %}
</body>
</html>