cababa/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.top_view, name='top_view'),
    path('user_agreement/', views.user_agreement_view, name='user_agreement_view'),
    path('cast_agreement/', views.cast_agreement_view, name='cast_agreement_view'),
    path('privacy_policy/', views.privacy_policy_view, name='privacy_policy_view'),
    path('cancel_policy/', views.cancel_policy_view, name='cancel_policy_view'),
    path('specified_commercial_transactions_act/', views.specified_commercial_transactions_act_view, name='specified_commercial_transactions_act_view'),
    path('system/', views.system_view, name='system_view'),
    path('admin/', admin.site.urls),
    path('pre_register/', include('pre_register.urls')),
    path('guest/', include('guest.urls')),
    path('hostess/', include('hostess.urls')),
    path('reservations/', include('reservations.urls')),
    path('staff/', include('staff.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guest/urls.py
from django.urls import path

from . import views

app_name = 'guest'

urlpatterns = [
    path('login/', views.GuestLoginView.as_view(), name='login'),
    path('callback/', views.GuestLoginCallbackView.as_view(), name='login_callback'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup/done/', views.SignUpDoneView.as_view(), name='signup_done'),
    path('bot/webhook/', views.LineBotWebhookView.as_view(), name='bot_webhook'),
]

staff/urls.py
from django.urls import path

from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.StaffTopView.as_view(), name='top'),
    path('login/', views.StaffLoginView.as_view(), name='login'),
    path('logout/', views.StaffLogoutView.as_view(), name='logout'),
    path('signup/', views.StaffSignupView.as_view(), name='signup'),
    path('confirm/', views.SignupConfirmView.as_view(), name='signup_confirm'),
    path('me/edit/', views.StaffEditMeView.as_view(), name='edit_me'),

    path('staff/', views.StaffListView.as_view(), name='staff_list'),
    path('staff/new/', views.StaffCreateView.as_view(), name='staff_create'),
    path('staff/<str:staff_id>/', views.StaffDetailView.as_view(), name='staff_detail'),
    path('staff/<str:staff_id>/edit/', views.StaffEditView.as_view(), name='staff_edit'),
    path('staff/<str:staff_id>/delete/', views.StaffDeleteView.as_view(), name='staff_delete'),

    path('hostess/', views.HostessListView.as_view(), name='hostess_list'),
    path('hostess/new/', views.HostessCreateView.as_view(), name='hostess_create'),
    path('hostess/invite/', views.HostessInviteView.as_view(), name='hostess_invite'),
    path('hostess/<str:hostess_id>/', views.HostessDetailView.as_view(), name='hostess_detail'),
    path('hostess/<str:hostess_id>/edit/', views.HostessEditView.as_view(), name='hostess_edit'),

    path('reservation/', views.ReservationListView.as_view(), name='reservation_list'),
]

staff/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from lib.models import BaseModel
from users.models import User


class OTP(BaseModel, models.Model):
    otp_id = models.UUIDField(_('otp_id'), default=uuid.uuid4, unique=True, db_index=True)
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, db_index=True)

staff/views.py
import japanmap

from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.base import View
from django.contrib.auth import logout
from django.conf import settings

from lib import mixins
from users import models as user_models
from reservations import models as reservation_models
from . import models, forms, services


class StaffLoginView(View):
    template = 'staff/account/login.html'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        form = forms.LoginForm(request.POST, context={'request': request})
        if not form.is_valid():
            context = dict(form=form)
            return render(request, self.template, context)
        form.save()
        redirect_to = request.GET.get('redirect_to')
        if redirect_to:
            return redirect(redirect_to)
        return redirect('staff:top')


class StaffLogoutView(mixins.StaffPageMixin, View):
    def get(self, request):
        logout(request)
        return redirect('staff:login')


class StaffSignupView(View):
    template = 'staff/account/signup.html'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        form = forms.SignupForm(request.POST, context={'request': request})
        if not form.is_valid():
            context = dict(form=form)
            return render(request, self.template, context)
        user = form.save()
        return render(request, 'staff/account/signup_done.html')


class SignupConfirmView(View):
    template = 'staff/account/signup_confirm.html'

    def get_queryset(self, otp_id):
        querysets = models.OTP.objects.filter(otp_id=otp_id).first()
        return querysets

    def get(self, request):
        otp_id = request.GET.get('token')
        otp = self.get_queryset(otp_id)
        context = {'otp': otp}
        return render(request, self.template, context)

    def post(self, request):
        form = forms.SignupConfirmForm(request.POST, context={'request': request})
        if not form.is_valid():
            otp_id = request.GET.get('token')
            otp = self.get_queryset(otp_id)
            context = dict(form=form, otp=otp)
            return render(request, self.template, context)
        user = form.save()
        return redirect('staff:top')


class StaffTopView(mixins.StaffPageMixin, View):
    template = 'staff/top.html'

    def get(self, request):
        return render(request, self.template)


class StaffListView(mixins.StaffPageMixin, View):
    template = 'staff/staff/list.html'

    def get_queryset(self, request):
        user = request.user
        querysets = user_models.User.objects.filter(group=user.group, user_type=user_models.User.UserTypes.STAFF).exclude(username=user.username)
        return querysets

    def get(self, request):
        page_obj = self.get_queryset(request)
        context = {'page_obj': page_obj}
        return render(request, self.template, context)


class StaffCreateView(mixins.StaffPageMixin, View):
    template = 'staff/staff/new.html'

    def get(self, request):
        context = {}
        return render(request, self.template, context)
    
    def post(self, request):
        form = forms.StaffForm(request.POST, context={'request': request})
        if not form.is_valid():
            context = dict(form=form)
            return render(request, self.template, context)
        otp = form.create()
        service = services.StaffService()
        service.send_registration_otp(otp)
        return redirect(reverse('staff:staff_list'))


class StaffDetailView(mixins.StaffPageMixin, View):
    template = 'staff/staff/detail.html'

    def get_queryset(self, staff_id):
        querysets = user_models.User.objects.get(user_id=staff_id, user_type=user_models.User.UserTypes.STAFF)
        return querysets

    def get(self, request, staff_id):
        querysets = self.get_queryset(staff_id)
        context = {'staff': querysets}
        return render(request, self.template, context)

class StaffEditView(mixins.StaffPageMixin, View):
    template = 'staff/staff/edit.html'

    def get_queryset(self, staff_id):
        querysets = user_models.User.objects.get(user_id=staff_id, user_type=user_models.User.UserTypes.STAFF)
        return querysets

    def get(self, request, staff_id):
        querysets = self.get_queryset(staff_id)
        context = {'staff': querysets}
        return render(request, self.template, context)

    def post(self, request, staff_id):
        querysets = self.get_queryset(staff_id)
        form = forms.StaffForm(request.POST, context={'request': request, 'staff': querysets})
        if not form.is_valid():
            context = dict(form=form)
            return render(request, self.template, context)
        user = form.update()
        return redirect(reverse('staff:staff_detail', kwargs=dict(staff_id=querysets.user_id)))


class StaffDeleteView(mixins.StaffPageMixin, View):
    def get_queryset(self, staff_id):
        querysets = user_models.User.objects.get(user_id=staff_id, user_type=user_models.User.UserTypes.STAFF)
        return querysets

    def post(self, request, staff_id):
        staff = self.get_queryset(staff_id)
        staff.delete()
        return redirect('staff:staff_list')


class StaffEditMeView(mixins.StaffPageMixin, View):
    template = 'staff/staff/edit_me.html'

    def get(self, request):
        context = {}
        return render(request, self.template, context)

    def post(self, request):
        form = forms.StaffEditMeForm(request.POST, context={'request': request})
        if not form.is_valid():
            context = dict(form=form)
            return render(request, self.template, context)
        user = form.update()
        return redirect('staff:edit_me')


class HostessListView(mixins.StaffPageMixin, View):
    template = 'staff/hostess/list.html'

    def get_queryset(self):
        querysets = user_models.User.objects.filter(user_type=user_models.User.UserTypes.HOSTESS, group=self.request.user.group).order_by('-date_joined')
        return querysets

    def get(self, request):
        page_obj = self.get_queryset()
        context = {'page_obj': page_obj}
        return render(request, self.template, context)


class HostessCreateView(mixins.StaffPageMixin, View):
    template = 'staff/hostess/new.html'

    def get_prefectures(self):
        prefectures = []
        for name, code in zip(japanmap.pref_names, list(range(len(japanmap.pref_names)))):
            prefectures.append(dict(
                name=name,
                code=code
            ))
        prefectures[0]['name'] = '非公開'
        return prefectures

    def get(self, request):
        form = forms.HostessForm()
        context = dict(form=form, prefectures=self.get_prefectures())
        return render(request, self.template, context)
    
    def post(self, request):
        form = forms.HostessForm(request.POST, request.FILES, context={'request': request})
        if not form.is_valid():
            context = dict(form=form, prefectures=self.get_prefectures())
            return render(request, self.template, context)
        hostess = form.create()
        return redirect(reverse('staff:hostess_list'))


class HostessDetailView(mixins.StaffPageMixin, View):
    template = 'staff/hostess/detail.html'

    def get_queryset(self, hostess_id):
        querysets = user_models.User.objects.get(user_id=hostess_id, user_type=user_models.User.UserTypes.HOSTESS, group=self.request.user.group)
        return querysets

    def get(self, request, hostess_id):
        querysets = self.get_queryset(hostess_id)
        context = {'hostess': querysets}
        return render(request, self.template, context)

class HostessEditView(mixins.StaffPageMixin, View):
    template = 'staff/hostess/edit.html'

    def get_queryset(self, hostess_id):
        querysets = user_models.User.objects.get(user_id=hostess_id, user_type=user_models.User.UserTypes.HOSTESS, group=self.request.user.group)
        return querysets
    
    def get_prefectures(self):
        prefectures = []
        for name, code in zip(japanmap.pref_names, list(range(len(japanmap.pref_names)))):
            prefectures.append(dict(
                name=name,
                code=code
            ))
        prefectures[0]['name'] = '非公開'
        return prefectures

    def get(self, request, hostess_id):
        hostess = self.get_queryset(hostess_id)
        form = forms.HostessForm()
        context = dict(form=form, hostess=hostess, prefectures=self.get_prefectures())
        return render(request, self.template, context)

    def post(self, request, hostess_id):
        querysets = self.get_queryset(hostess_id)
        form = forms.HostessEditForm(request.POST, context={'request': request, 'hostess': querysets})
        if not form.is_valid():
            context = dict(form=form)
            return render(request, self.template, context)
        hostess = form.update()
        return redirect(reverse('staff:hostess_detail', kwargs=dict(hostess_id=querysets.user_id)))


class HostessInviteView(mixins.StaffPageMixin, View):
    template = 'staff/hostess/invite.html'

    def get(self, request):
        invitation_url = 'https://' + settings.HOST_NAME + reverse('hostess:invite_group', kwargs=dict(group_id=request.user.group.group_id))
        context = dict(invitation_url=invitation_url)
        return render(request, self.template, context)


class ReservationListView(mixins.StaffPageMixin, View):
    template = 'staff/reservation/list.html'

    def get_queryset(self):
        querysets = reservation_models.Reservation.objects.filter(time__hostess__group=self.request.user.group).order_by('-created_at')
        return querysets

    def get(self, request):
        page_obj = self.get_queryset()
        context = {'page_obj': page_obj}

staff/templates/staff-partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | CABABA</title>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
    {% include 'staff-partials/header.html' %}

    <div class="container">
        <div class="wrapper-container">
            {% block content %}{% endblock %}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'main.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

staff/templates/staff-partials/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'staff:top' %}">
        <img src="{% static 'images/title.svg' %}" height="30" class="d-inline-block align-top" alt="">
    </a>

    {% if request.user.email %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- お嬢管理 -->
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        お嬢管理
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'staff:hostess_list' %}">お嬢一覧</a>
                        <a class="dropdown-item" href="{% url 'staff:hostess_create' %}">お嬢登録</a>
                        <a class="dropdown-item" href="{% url 'staff:hostess_invite' %}">お嬢招待</a>
                    </div>
                </li>
            </ul>
            <!-- お嬢管理 -->
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        予約管理
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'staff:reservation_list' %}">予約一覧</a>
                    </div>
                </li>
            </ul>
            <!-- スタッフ管理 -->
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        スタッフ管理
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'staff:staff_list' %}">スタッフ一覧</a>
                        <a class="dropdown-item" href="{% url 'staff:staff_create' %}">スタッフ登録</a>
                    </div>
                </li>
            </ul>
        </div>

        <!-- ログインユーザー機能 -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user.group.name }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown2">
                    <a class="dropdown-item" href="{% url 'staff:edit_me' %}">{{ request.user.last_name }}{{ request.user.first_name }}</a>
                    <a class="dropdown-item" href="{% url 'staff:logout' %}">ログアウト</a>
                </div>
            </li>
        </ul>
    {% endif %}
  </nav>